// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Seven11Eleven/jwt_auth_gybernaty/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RefreshTokenService is an autogenerated mock type for the RefreshTokenService type
type RefreshTokenService struct {
	mock.Mock
}

// CreateAccessToken provides a mock function with given fields: author, expired
func (_m *RefreshTokenService) CreateAccessToken(author *domain.Author, expired int) (string, error) {
	ret := _m.Called(author, expired)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Author, int) (string, error)); ok {
		return rf(author, expired)
	}
	if rf, ok := ret.Get(0).(func(*domain.Author, int) string); ok {
		r0 = rf(author, expired)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.Author, int) error); ok {
		r1 = rf(author, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRefreshToken provides a mock function with given fields: author, expired
func (_m *RefreshTokenService) CreateRefreshToken(author *domain.Author, expired int) (string, error) {
	ret := _m.Called(author, expired)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Author, int) (string, error)); ok {
		return rf(author, expired)
	}
	if rf, ok := ret.Get(0).(func(*domain.Author, int) string); ok {
		r0 = rf(author, expired)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.Author, int) error); ok {
		r1 = rf(author, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractIDFromToken provides a mock function with given fields: tokenRequested
func (_m *RefreshTokenService) ExtractIDFromToken(tokenRequested string) (uuid.UUID, error) {
	ret := _m.Called(tokenRequested)

	if len(ret) == 0 {
		panic("no return value specified for ExtractIDFromToken")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return rf(tokenRequested)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(tokenRequested)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenRequested)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthorByID provides a mock function with given fields: ctx, id
func (_m *RefreshTokenService) GetAuthorByID(ctx context.Context, id uuid.UUID) (*domain.Author, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByID")
	}

	var r0 *domain.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Author, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Author); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshTokenService creates a new instance of RefreshTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenService {
	mock := &RefreshTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
