version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} # Установите пароль для суперпользователя
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432" # Обратите внимание на правильный порт
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - ./.env:/src/.env
    command: ["/bin/server"]

volumes:
  db_data:
