services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}     
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
  
  migrate:
    image: migrate/migrate:v4.14.1
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "sh", "-c",
      "until nc -z db 5432; do sleep 2; done; migrate -path=/migrations -database postgres://user:pass@db:5432/gybernaty?sslmode=disable up" #замените up на down с флагом -all, чтобы после запуска сервиса migrate он применил down  
    ]
    
    depends_on:
      - db
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - ./.env:/src/.env
    command: ["/bin/server"]

volumes:
  db_data:
